name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image: [7.4, 7.4-ioncube]
        experimental: [false]

    continue-on-error: ${{ matrix.experimental }}

    name: Image:${{ matrix.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.image }}
          tags: kevindierkx/php-ci:${{ matrix.image }}
          push: true

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
